export const REQUEST_NOTES = 'REQUEST_NOTES';
export const REQUEST_NOTES_SUCCESS = 'REQUEST_NOTES_SUCCESS';
export const REQUEST_NOTES_ERROR = 'REQUEST_NOTES_ERROR';

export const ADD_NOTE = 'ADD_NOTE';
export const ADD_NOTE_SUCCESS = 'ADD_NOTE_SUCCESS';
export const ADD_NOTE_ERROR = 'ADD_NOTE_ERROR';

export const DELETE_NOTE = 'DELETE_NOTE';
export const DELETE_NOTE_SUCCESS = 'DELETE_NOTE_SUCCESS';
export const DELETE_NOTE_ERROR = 'DELETE_NOTE_ERROR';

export const MOVE_NOTE = 'MOVE_NOTE';

